spring.application.name=taller-cicd-springboot

# Base de datos H2 en memoria (ideal para el pipeline de CI, no necesita BD externa)
spring.datasource.url=jdbc:h2:mem:tallerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
